### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by daddykotex** [awslabs/smithy-language-server#79]
We have a working formatter and we're currently looking at integrating it with our VS Code extension. The ideal solution is as follow:

1. we add a dependency here
2. use the dependency to format the code by activating: `capabilities.setDocumentFormattingProvider(true);` and implementing: `CompletableFuture<List<? extends TextEdit>> formatting(DocumentFormattingParams params)`

I have a working prototype, happy to PR if you're interested. The source for the formatter is here: https://github.com/disneystreaming/smithy-translate/pull/16

It is a scala project. If we are to add a dependency, it would be shaded in the same way the dependency on coursier-interface is.

Less interesting approaches include: 

1. cross compiling to javascript and including it as part of our vscode extension
2. shelling out to an external process to run the formatting as part of our vscode extension (also much slower)
3. cross compiling to javascript and including it as part of a separate vscode extension
4. shelling out to an external process to run the formatting as part of a separate vscode extension (also much slower)

These approaches are less interesting because we're the only one benefitting from the formatter. Where as if it's included in the LSP every client get's it for free.

**Comment by daddykotex** [comment]
There is also an alternative to the ideal solution which is to use coursier to fetch the formatter on the fly rather than to have an hard-wired dependency in the build. This would allow us to configure the formatter version (in the smithy-build.json), maybe even have a configuration for the formatter.

**Comment by srchase** [comment]
This was completed in https://github.com/awslabs/smithy-language-server/pull/89
