### ISSUE TITLE
[feature-request] become a `documentSymbolProvider`

### ISSUE THREAD

**Issue by ckipp01** [awslabs/smithy-language-server#87]
I'm really loving having a language server for Smithy so far. Thanks for making the effort and having one! One missing feature that I've found myself reaching for is `textDocument/documentSymbol`. You can read more about it [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol), but especially when I'm working with large smithy files it'd be great to use this to get a nice overview of everything in the file or quickly search for something intelligently in the current document.

**Comment by kubukoz** [comment]
I'm a huge fan of this idea - e.g. in vscode, this powers at least 3 features:

- breadcrumbs
- find symbol in document
- document outline view

so it would be a pretty big win.

**Comment by kubukoz** [comment]
FYI I've started some work on this :)

**Comment by mtdowling** [comment]
Btw, I’m also working on a fault tolerant parse tree that I think will be the basis of rewriting lots of this repo.

**Comment by kubukoz** [comment]
That sounds very useful! However, I'm still going to submit this PR as it's almost ready and it's standing on existing shoulders of existing giants (the location map in `SmithyProject` is of HUGE help!) :)

**Comment by mtdowling** [comment]
Awesome, thanks! I didn’t realize it was already done. Should be easy enough to refactor stuff in the future as needed when the parser stuff is done 😊
