### ISSUE TITLE
Go-to definition selects a bigger region than expected

### ISSUE THREAD

**Issue by zetashift** [awslabs/smithy-language-server#96]
I am hitting a problem where the "go-to definition" selects more than it should:
- Press go to definition on a shape ( in my case GetCustomerInput )
- It'll select a few more lines than it should
    
![image](https://user-images.githubusercontent.com/1857826/229629058-728aa244-ec2e-48c4-844d-314bb301291a.png)

(notice how `@output` is also selected, even tho it's not part of that shape).

Below you'll find some screen recordings because I have trouble with explaining the behaviour :P.

## Details

I tried this using VSCode and Helix and got the same kind of "selection too big" behaviour.

## Reproduction

- With the following smithy code, try doing go-to-definition on several shapes and you'll see the selection sortof off?
- You might have to use the format code option first

```smithy
$version: "2"

namespace foo

resource Customer {
    identifiers: {
        customerId: String
    }
    properties: {
        name: String
    }
    read: GetCustomer
}

@readonly
@http(method: "GET", uri: "/customers/{customerId}", code: 200)
operation GetCustomer {
    input: GetCustomerInput
    output: GetCustomerOutput
}

@input
structure GetCustomerInput for Customer {
    @httpLabel
    @required
    $customerId
}

@output
structure GetCustomerOutput for Customer {
    @required
    $customerId
    $name
}
```
VSCode ( _note this one is really quick, but you'll see for a second that a bigger region is "highlighted"_ ): 
![Peek 2023-04-03 23-11](https://user-images.githubusercontent.com/1857826/229629358-1fa5c92f-f6b3-4458-8a33-98349297911b.gif)
Helix: 
![Peek 2023-04-03 23-13](https://user-images.githubusercontent.com/1857826/229629360-a3947f38-0836-4a9f-a582-3aef44abfa4e.gif)

**Comment by srchase** [comment]
You mentioned formatting. Are you manually invoking the formatting? Or is that happening automatically (for example with `editor.formatOnSave` and `file.autoSave` both enabled for VS Code)?

Does this occur all the time? Or only after formatting is applied?

**Comment by zetashift** [comment]
I manually invoke the formatting! I never used any "format on save" functions.

I don't have a lot of smithy projects that I can sample off, but I believe it occurs all the time. Restarting the editor doesn't change the behaviour either.

**Comment by srchase** [comment]
@zetashift Can you confirm that this issue was resolved by the fix in https://github.com/awslabs/smithy-language-server/pull/98?

**Comment by zetashift** [comment]
Yup thank you, go to definition works now in VSCode!
